export type DocsRoute = { path: string; title: string; description: string };

type PagefindHit = { url: string; meta: { title?: string }; excerpt: string };
type Pagefind = {
	search: (query: string) => Promise<{ results: Array<{ data: () => Promise<PagefindHit> }> }>;
};

const MAX_RESULTS = 5;
const PAGEFIND_URL = '/pagefind/pagefind.js';

let pagefind: Pagefind | null = null;

function isPagefind(value: unknown): value is Pagefind {
	return typeof value === 'object' && value !== null && 'search' in value && typeof value.search === 'function';
}

async function loadPagefind(): Promise<Pagefind | null> {
	if (pagefind) return pagefind;
	try {
		const mod: unknown = await import(/* @vite-ignore */ PAGEFIND_URL);
		if (!isPagefind(mod)) return null;
		pagefind = mod;
		return mod;
	} catch {
		return null;
	}
}

function stripMarkup(html: string): string {
	const el = document.createElement('div');
	el.innerHTML = html;
	return (el.textContent ?? '').replace(/\s+/g, ' ').trim();
}

function normalise(value: string): string {
	return value.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
}

function scoreMatch(candidate: string, spoken: string): number {
	const a = normalise(candidate);
	const b = normalise(spoken);
	if (!a || !b) return 0;
	if (a === b) return 100;
	if (a.startsWith(b) || b.startsWith(a)) return 80;
	if (a.includes(b) || b.includes(a)) return 60;
	const words = b.split(' ').filter((w) => w.length > 2);
	const hits = words.filter((w) => a.includes(w)).length;
	return words.length ? (hits / words.length) * 50 : 0;
}

export function findRoute(routes: DocsRoute[], spoken: string): DocsRoute | null {
	const ranked = routes
		.map((route) => ({
			route,
			score: Math.max(scoreMatch(route.title, spoken), scoreMatch(route.description, spoken) * 0.6),
		}))
		.sort((a, b) => b.score - a.score);
	const best = ranked[0];
	return best && best.score >= 40 ? best.route : null;
}

export async function searchDocs(query: string) {
	const engine = await loadPagefind();
	if (!engine) {
		return {
			status: 'unavailable' as const,
			message: 'The search index is only generated by a production build, so search is offline here.',
		};
	}
	const found = await engine.search(query);
	const top = await Promise.all(found.results.slice(0, MAX_RESULTS).map((hit) => hit.data()));
	if (!top.length) return { status: 'empty' as const, query };
	return {
		status: 'ok' as const,
		total: found.results.length,
		results: top.map((hit) => ({
			title: hit.meta.title ?? hit.url,
			url: hit.url,
			excerpt: stripMarkup(hit.excerpt),
		})),
	};
}

function headings(): HTMLHeadingElement[] {
	return [...document.querySelectorAll<HTMLHeadingElement>('.sl-markdown-content h2, .sl-markdown-content h3')];
}

function currentHeading(): HTMLHeadingElement | null {
	const all = headings();
	if (!all.length) return null;
	const passed = all.filter((h) => h.getBoundingClientRect().top <= 120);
	return passed.length ? passed[passed.length - 1] : all[0];
}

export function readSection() {
	const heading = currentHeading();
	const title = document.querySelector('.sl-markdown-content')?.closest('main')?.querySelector('h1');
	if (!heading) {
		const intro = document.querySelector('.sl-markdown-content');
		const text = intro ? (intro.textContent ?? '').replace(/\s+/g, ' ').trim() : '';
		return text
			? { status: 'ok' as const, heading: title?.textContent?.trim() ?? document.title, text }
			: { status: 'empty' as const };
	}
	const parts: string[] = [];
	let node = heading.closest('.sl-heading-wrapper')?.nextElementSibling ?? heading.nextElementSibling;
	while (node && !node.matches('h2, .sl-heading-wrapper')) {
		const text = (node.textContent ?? '').replace(/\s+/g, ' ').trim();
		if (text) parts.push(text);
		node = node.nextElementSibling;
	}
	return {
		status: 'ok' as const,
		heading: heading.textContent?.replace(/\s+/g, ' ').trim() ?? '',
		text: parts.join(' ') || 'This section has no body text.',
	};
}

export function showExample(language: string) {
	const tabs = [...document.querySelectorAll<HTMLElement>('[role="tab"]')];
	if (!tabs.length) return { status: 'no_examples' as const, message: 'This page has no multi-language examples.' };
	const ranked = tabs
		.map((tab) => ({ tab, score: scoreMatch(tab.textContent ?? '', language) }))
		.sort((a, b) => b.score - a.score);
	const best = ranked[0];
	if (!best || best.score < 40) {
		return {
			status: 'not_found' as const,
			available: [...new Set(tabs.map((t) => (t.textContent ?? '').trim()))],
		};
	}
	best.tab.click();
	best.tab.scrollIntoView({ block: 'center', behavior: 'smooth' });
	return { status: 'ok' as const, language: (best.tab.textContent ?? '').trim() };
}
