import { conflict, forbidden, unauthorized } from '../../shared/errors';
import { describeError, logStructured } from '../../shared/logger';
import { generateToken, hashToken } from '../../shared/security/tokens';
import { AuthRepository, type Tx } from './auth.repository';

export type UserPrincipal = {
  kind: 'user';
  userId: string;
  deviceId: string;
  sessionId: string;
  installId: string;
};

export type IssuedSession = { status: 'registered' | 'refreshed'; session_token: string; expires_in: number };

export type AuthSettings = { tokenSecret: string; sessionTtlSeconds: number; refreshGraceSeconds: number };

const INSTALL_TAKEN = 'Install id is already registered';

/**
 * Opaque, device-bound sessions (docs: architecture/security, "Authentication").
 *
 * - A token is 256 random bits; only its HMAC is stored.
 * - Every token is bound to the device's install id. A request must present both, and they must
 *   match, so a token copied without its install id is useless and vice versa.
 * - Tokens are only ever generated by the server. Registering or refreshing revokes the device's
 *   previous sessions, so there is one live session per device and no fixation.
 * - Knowing an install id is not enough to register as that device: re-registering an existing
 *   install requires that device's current session. Without one, the client gets 409 and starts a
 *   new install. Unverified phone hashes never link an install to an existing account.
 */
export class AuthService {
  constructor(
    private readonly repo: AuthRepository,
    private readonly settings: AuthSettings,
  ) {}

  private hash(token: string): string {
    return hashToken(this.settings.tokenSecret, token);
  }

  private async issue(tx: Tx, deviceId: string, status: IssuedSession['status']): Promise<IssuedSession> {
    const token = generateToken('session');
    await this.repo.insertSession(tx, deviceId, this.hash(token), this.settings.sessionTtlSeconds);
    return { status, session_token: token, expires_in: this.settings.sessionTtlSeconds };
  }

  async register(input: {
    installId: string;
    model: string;
    locale: 'am-ET' | 'en-US';
    presentedToken: string | null;
  }): Promise<IssuedSession> {
    return this.repo.transaction(async (tx) => {
      const existing = await this.repo.lockDeviceByInstallId(tx, input.installId);
      if (!existing) {
        const created = await this.repo.createUserWithDevice(tx, input);
        // Lost a race with a concurrent registration of the same install id.
        if (!created) throw conflict(INSTALL_TAKEN);
        return this.issue(tx, created.deviceId, 'registered');
      }

      // Same response whether the token is missing or wrong: no oracle for guessing.
      if (!input.presentedToken) throw conflict(INSTALL_TAKEN);
      const live = await this.repo.findActiveDeviceSession(tx, existing.deviceId, this.hash(input.presentedToken));
      if (!live) throw conflict(INSTALL_TAKEN);
      if (existing.userDeletedAt) throw conflict(INSTALL_TAKEN);
      if (existing.userStatus !== 'active') throw forbidden('Account suspended');

      await this.repo.revokeDeviceSessions(tx, existing.deviceId);
      await this.repo.touchDevice(tx, existing.deviceId, input.model);
      return this.issue(tx, existing.deviceId, 'registered');
    });
  }

  /**
   * Resolves a bearer token and install id to a principal, or throws 401/403.
   * 401 for anything wrong with the credential (missing, unknown, expired, revoked, wrong device,
   * account being deleted) with one message; 403 only for a valid credential on a suspended account.
   */
  async authenticate(token: string | null, installId: string | undefined, options: { allowPendingDeletion?: boolean } = {}): Promise<UserPrincipal> {
    if (!token || !installId) throw unauthorized();
    const session = await this.repo.findSessionByHash(this.hash(token));
    if (!session) throw unauthorized();
    if (session.revokedAt !== null) throw unauthorized();
    if (session.expiresAt.getTime() <= Date.now()) throw unauthorized();
    if (session.installId !== installId) throw unauthorized();
    if (session.userDeletedAt !== null && !options.allowPendingDeletion) throw unauthorized();
    if (session.userStatus !== 'active') throw forbidden('Account suspended');

    this.repo.touchDeviceThrottled(session.deviceId).catch((error: unknown) => {
      logStructured('auth.touch_failed', describeError(error));
    });
    return {
      kind: 'user',
      userId: session.userId,
      deviceId: session.deviceId,
      sessionId: session.sessionId,
      installId: session.installId,
    };
  }

  /**
   * Rotates a session: the presented token is revoked and a new one issued. A token that expired
   * less than AUTH_REFRESH_GRACE_SECONDS ago may still be refreshed, so a phone that was offline
   * for a while does not lose its account. A revoked token never can.
   */
  async refresh(token: string | null, installId: string | undefined): Promise<IssuedSession> {
    if (!token || !installId) throw unauthorized();
    return this.repo.transaction(async (tx) => {
      const session = await this.repo.findSessionByHash(this.hash(token), tx);
      if (!session || session.revokedAt !== null || session.installId !== installId) throw unauthorized();
      if (session.expiresAt.getTime() + this.settings.refreshGraceSeconds * 1000 <= Date.now()) throw unauthorized();
      if (session.userDeletedAt !== null) throw unauthorized();
      if (session.userStatus !== 'active') throw forbidden('Account suspended');
      // Exactly one concurrent refresh of the same token wins.
      if (!(await this.repo.revokeSession(session.sessionId, tx))) throw unauthorized();
      return this.issue(tx, session.deviceId, 'refreshed');
    });
  }

  async logout(principal: UserPrincipal): Promise<void> {
    await this.repo.revokeSession(principal.sessionId);
  }
}
